const fs = require('fs');
const path = '../client/src/pages/Admin.tsx';
let content = fs.readFileSync(path, 'utf8');

// Add the import for legacyData3
content = content.replace("import { oldProjects } from '../data/oldProjects';", "import { oldProjects } from '../data/oldProjects';\nimport { oldEducation, oldExperience } from '../data/legacyData3';");

// Add handleMigrateEducation and handleMigrateExperience functions
const migrateFunctions = `
  const handleMigrateEducation = async () => {
    if (window.confirm("Migrate 11 hardcoded education items to Firestore?")) {
      for (const edu of oldEducation) {
        await addDoc(collection(db, "education"), edu);
      }
      alert("Education Migration successful!");
    }
  };

  const handleMigrateExperience = async () => {
    if (window.confirm("Migrate 4 hardcoded experience items to Firestore?")) {
      for (const exp of oldExperience) {
        await addDoc(collection(db, "experience"), exp);
      }
      alert("Experience Migration successful!");
    }
  };
`;
content = content.replace("const handleMigrate = async () => {", migrateFunctions + "\n  const handleMigrate = async () => {");

// Add the buttons to the placeholders in the tabs
content = content.replace(/{activeTab !== 'projects' && \([\s\S]*?\)}/, `{activeTab === 'education' && (
          <div>
            <h2>Manage Education</h2>
            <hr style={{ borderColor: '#333' }} />
            <button onClick={handleMigrateEducation} className="btn btn-warning mb-4">Migrate 11 Education Items</button>
            <div className="alert alert-info">Full Editor coming soon! You can migrate data now.</div>
          </div>
        )}
        
        {activeTab === 'experience' && (
          <div>
            <h2>Manage Experience</h2>
            <hr style={{ borderColor: '#333' }} />
            <button onClick={handleMigrateExperience} className="btn btn-warning mb-4">Migrate 4 Experience Items</button>
            <div className="alert alert-info">Full Editor coming soon! You can migrate data now.</div>
          </div>
        )}
        
        {activeTab !== 'projects' && activeTab !== 'education' && activeTab !== 'experience' && (
          <div>
            <h2>Manage {activeTab.charAt(0).toUpperCase() + activeTab.slice(1)}</h2>
            <hr style={{ borderColor: '#333' }} />
            <div className="alert alert-info">
              The {activeTab} editor is being generated by the AI...
            </div>
          </div>
        )}`);

fs.writeFileSync(path, content);
console.log("Admin panel updated with migration buttons for Education and Experience!");
